Repository prashantkalokhe/Hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#1 Create Java Full stack
  Java Full stack
Labels: good first issue

#7 Added new folder for java GUI code and created some examples using javafx
  JavaFX_Examples/ControlsDemo.java
  JavaFX_Examples/EventFxDemo.java
  JavaFX_Examples/Main.java
  JavaFX_Examples/readme.md
Labels: good first issue

#2 Added Heap Sort in Java
  heapsort.java
Labels: Hacktoberfest

#8 Java gui
  Java_Swing_Examples/TextFieldDemo.java
  Java_Swing_Examples/borderDemo.java
  Java_Swing_Examples/checkboxDemo.java
  Java_Swing_Examples/demo1.java
  Java_Swing_Examples/layeredPaneDemo.java
  Java_Swing_Examples/readme.md
  Java_Swing_Examples/treeDemo.java
Labels: Hacktoberfest-accepted

#11 Create FactorialUsingRecursion
  FactorialUsingRecursion
Labels: Hacktoberfest-accepted

#17 This program demonstrates merge sort in java
  MergeSort.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#12 Create Queue1.java
  Queue1.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#13 Create CelciusToFarenheitMethod.java
  CelciusToFarenheitMethod.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#14 Create BestTimeToBuyandSellStock.java
  BestTimeToBuyandSellStock.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#16 added folder fo java dsa
  Java_DSA/MissingNumber/Main.java
  Java_DSA/isUnique/Main.java
  Java_DSA/maxProduct/Main.java
  Java_DSA/readme.md
  Java_DSA/searchValue/Main.java
  Java_DSA/twoSum/Main.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#15 Create Rock_paper_scissor.java
  Rock_paper_scissor.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#20 Create create JDBC Connection
  create JDBC Connection
Labels: Hacktoberfest, Hacktoberfest-accepted

#21 Create execute and read select queries using JDBC?
  execute and read select queries using JDBC?
Labels: Hacktoberfest, Hacktoberfest-accepted

#22 Create update a record in the database using JDBC
  update a record in the database using JDBC
Labels: Hacktoberfest, Hacktoberfest-accepted

#23 Create execute any type of query in JDBC
  execute any type of query in JDBC
Labels: Hacktoberfest, Hacktoberfest-accepted

#24 Create example code for JDBC prepared statement
  example code for JDBC prepared statement
Labels: Hacktoberfest, Hacktoberfest-accepted

#19 A valid squares using binary search written by myself!
  Valid_Squares.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#28 Create knapsack_using_fractional_method.cpp
  knapsack_using_fractional_method.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#27 Create Find_Duplicate_File_In_System.java
  Find_Duplicate_File_In_System.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#26 Added a Web-dev project
  TechCrunch.png
  bizinsider.png
  dog-img.jpg
  index.html
  iphone6.png
  lady-img.jpg
  mashable.png
  styles.css
  tnw.png
Labels: Hacktoberfest, Hacktoberfest-accepted

#30 Create quicksort.java
  quicksort.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#31 Adding Dijkstra Algorithm
  Dijsktra.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#35 Create swap.java
  swap.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#33 Update tiranga.java
  Core_java/indian Flag/src/tiranga.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#34 Create calculator Java
  calculator Java
Labels: Hacktoberfest, Hacktoberfest-accepted

#36 seive of erathosthenes
  Java_DSA/SieveOfEratosthenes.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#38 Rotated a linked list
  Java_DSA/Rotate a Linked List/Main.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#39 Added HTML project
  HTML project/Simple Survey Form/index.html
Labels: Hacktoberfest, Hacktoberfest-accepted

#40 Database python connectivity project
  Database python connectivity.py
Labels: Hacktoberfest, Hacktoberfest-accepted

#41 Create Delete Node in a Linked List
  Delete Node in a Linked List
Labels: Hacktoberfest, Hacktoberfest-accepted

#45 Create subsetsII.java
  Java_DSA/subsetsII.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#44 Create maximumGap
  Java_DSA/maximumGap
Labels: Hacktoberfest, Hacktoberfest-accepted

#43 Create combinationSum.java
  Java_DSA/combinationSum.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#42 Create reverse_prefix_of_word.java
  Java_DSA/reverse_prefix_of_word.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#50 CycleSort.java
  Java_DSA/CycleSort.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#48 Create Binary_SearchC++
  Binary_SearchC++.cpp
  First_and_Last_Occurance.cpp
  Recursive_Array_Summation.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#47 Inauguration page using html & css
  confetti.js
  index.html
  style.css
Labels: Hacktoberfest, Hacktoberfest-accepted

#46 added tower of hanoi code
  tower_of_hanoi.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#55 Create RotateLL.java
  RotateLL.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#54 Create Backtrack.java
  Backtrack.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#53 Level Order traversal of Binary Tree
  Java_DSA/Binary Tree Level Order Traversal/Solution.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#52 Add files via upload
  Reversedstring.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#60 Create calculator.cpp
  calculator.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#59 Create selection_sort.cpp
  selection_sort.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#58 Insertion_sort.cpp
  Insertion_sort.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#56 Create binarysearch.cpp
  binarysearch.cpp
  factorial.cpp
  fibonacci.cpp
  linear_to_decimal.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#61 circular queue operations
  HEAP SORT.c
  circularqueue.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#62 Priority Queue using linked list
  Priority Queue using linked list.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#78 Create simple program for CallableStatement statement to execute stor…
  simple program for CallableStatement statement to execute stored procedure
Labels: Hacktoberfest, Hacktoberfest-accepted

#77 Create to get primary key value (auto-generated keys) from inserted q…
  to get primary key value (auto-generated keys) from inserted queries using JDBC
Labels: Hacktoberfest, Hacktoberfest-accepted

#76 queue operations using Dynamic Array
  implement queue operations using Dynamic Array .cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#63 UniquePaths.java
  Java_DSA/UniquePaths.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#65 Guess-the-Number
  Guess The Number/Guess_number.py
  Guess The Number/README.md
  Guess The Number/best_score.txt
Labels: Hacktoberfest, Hacktoberfest-accepted

#70 Create QuickSort.java
  Java_DSA/Sorting/QuickSort.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#73 First Missing Positive Number in an array
  Java_DSF/FirstMissingPositive/Solution.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#74 Balance Brackets
  Java_DSA/Balance brackets (LeetCode)/Main.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#75 Create SearchinRotatedSortedArray.cpp
  SearchinRotatedSortedArray.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#79 Create program for CallableStatement statement with stored procedure …
  program for CallableStatement statement with stored procedure returns OUT parameters
Labels: Hacktoberfest, Hacktoberfest-accepted

#80 Create program for CallableStatement statement with batch execution
  program for CallableStatement statement with batch execution
Labels: Hacktoberfest, Hacktoberfest-accepted

#82 Added comments for easy understanding : )
  Guess The Number/Guess_number.py
Labels: Hacktoberfest, Hacktoberfest-accepted

#83 Added quick sort algorithm for easy understanding
  MergeSort.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#84 Added a basic definition of heap sort for easy understanding
  HEAP SORT.c
Labels: Hacktoberfest, Hacktoberfest-accepted

#85 Create BubbleSort.java
  Java_DSA/BubbleSort.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#105 CONTRIBUTED
  GCD USING EUCLID ALGO.C
  PRODUCT OF ELEMENT USING O(1).c
  ROUND OFF MATRIX.c
  SQUAREROOT_USING_FOUR_ARTHIMATIC_OPERATION.C
  SWAP CYCLE.c
Labels: Hacktoberfest, Hacktoberfest-accepted

#86 add student java files
  Student.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#88 Rock-Paper-Scissors
  Rock Paper Scissors/README.md
  Rock Paper Scissors/Rock_Paper_Scissors.py
Labels: Hacktoberfest, Hacktoberfest-accepted

#106 Trailing numbers
  Trailing numbers.py
Labels: Hacktoberfest, Hacktoberfest-accepted

#104 CODE CHEFS
  CHEFSTEP.cpp
  CHFDBT.cpp
  ICL1902.cpp
  POOK.cpp
  SRTARR.cpp
  TALAZY.cpp
  TRAVELPS.cpp
  VOTERS.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#103 Create diagonal_sum.java
  diagonal_sum.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#89 MouseListener , MouseMotionListener
  HTML project/Survey Form/Survey_Form.html
  Java_Swing_Examples/KeyDemo.java
  Java_Swing_Examples/MouseDemo.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#95 Created ValidParentheses.cpp
  ValidParentheses.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#90 Create element_frequency.java
  element_frequency.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#102 Java and javascipt codes
  Tree-sort_algo.java
  flg_panel.js
Labels: Hacktoberfest, Hacktoberfest-accepted

#101 Create validPalindrome.java
  Java_DSA/validPalindrome.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#91 created MajorityElement.java
  Java_DSA/MajorityElement.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#93 Create MaximumAverageSubarray.cpp
  MaximumAverageSubarray.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#94 Created MissingNumber.cpp
  MissingNumber.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#96 Leetcode
  Java_DSA/merge sorted arrays
  Java_DSA/sortColors.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#97 Create jump II.java
  Java_DSA/jump II.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#98 Create tribo.java
  Java_DSA/tribo.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#99 Create climbStairs.java
  Java_DSA/climbStairs.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#100 Create bestTimeToSellStocks.java
  Java_DSA/bestTimeToSellStocks.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#108 Add files via upload
  GUESS NUMBER.c
Labels: Hacktoberfest, Hacktoberfest-accepted

#138 color change on button click in java
  Java_Swing_Examples/Background Color Cycle in java/ColorCycle.class
  Java_Swing_Examples/Background Color Cycle in java/ColorCycle.java
  Java_Swing_Examples/Background Color Cycle in java/Screenshot 1.jpg
  Java_Swing_Examples/Background Color Cycle in java/Screenshot 2.jpg
  Java_Swing_Examples/Background Color Cycle in java/Screenshot 3.jpg
  Java_Swing_Examples/Background Color Cycle in java/Screenshot 4.jpg
Labels: Hacktoberfest, Hacktoberfest-accepted

#134 Container With Most Water Leetcode
  Container With Most Water.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#126 Create CaseCheck.java
  CaseCheck.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#120 Create linked list reversal
  Java_DSA/linked list reversal
Labels: Hacktoberfest, Hacktoberfest-accepted

#114 activity_selection.c
  activity_selection.c
Labels: Hacktoberfest, Hacktoberfest-accepted

#112 huffman.cpp
  checkprime.c
  huffman.cpp
  optimised_prime.c
Labels: Hacktoberfest, Hacktoberfest-accepted

#140 Missing Number [1,n]
  Java_DSA/Missing Number [1,n]/Main.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#117 optimised_checkprime.c
  optimised_checkprime.c
Labels: Hacktoberfest, Hacktoberfest-accepted

#116 evenodd_arrange.c
  evenodd_arrange.c
Labels: Hacktoberfest, Hacktoberfest-accepted

#115 swap_array.c
  swap_array.c
Labels: Hacktoberfest, Hacktoberfest-accepted

#113 Create piglatin.java
  piglatin.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#143 Full stack Development
  Full stack development/To-do-list/Screenshot.jpg
  Full stack development/To-do-list/To-do-list.html
Labels: Hacktoberfest, Hacktoberfest-accepted

#122 Create contains duplicate_leetcode
  Java_DSA/contains duplicate
Labels: Hacktoberfest, Hacktoberfest-accepted

#121 Create max consecutive ones_leetcode
  Java_DSA/max consecutive ones
Labels: Hacktoberfest, Hacktoberfest-accepted

#118 Create palindrome.js
  JavaScript/palindrome.js
Labels: Hacktoberfest, Hacktoberfest-accepted

#152 Update README.md
  README.md
Labels: Hacktoberfest, Hacktoberfest-accepted

#135 Added code to Reverse Integer Leetcode
  Reverse Integer.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#107 Add files via upload
  binary tree menu driven.c
Labels: Hacktoberfest, Hacktoberfest-accepted

#109 Create ellipse.java
  ellipse.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#150 Hacktoberfest2022
  Java_DSA/magicsquare.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#123 Majority Element
  Java_DSA/Majority Element/Main.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#124 Create CyclicSort.java
  Java_DSA/Sorting/CyclicSort.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#142 Maximum Average Subarray I
  Java_DSA/Maximum Average Subarray I/Main.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#133 jumpsearch.c
  jumpsearch.c
Labels: Hacktoberfest, Hacktoberfest-accepted

#141 socket programming
  client1.c
  client2.c
  server.c
Labels: Hacktoberfest, Hacktoberfest-accepted

#163 Added To-do app
  JavaScript/To Do App/index.html
  JavaScript/To Do App/script.js
  JavaScript/To Do App/style.css
Labels: Hacktoberfest, Hacktoberfest-accepted

#156 Full Stack Project (TIC TAC TOE)
  Tic Tac Toe/Main.py
Labels: Hacktoberfest, Hacktoberfest-accepted

#127 Create CountNums.java
  CountNums.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#136 Added code for Spiral Matrix Leetcode
  Spiral Matrix.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#128 Create Fibo.java
  Fibo.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#165 Rock Paper Scissors
  Rock Paper Scissors.py
Labels: Hacktoberfest, Hacktoberfest-accepted

#164 LeetCode Hard
  Java_DSA/First_missing_positive.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#161 created missing number
  shalu461975
Labels: Hacktoberfest, Hacktoberfest-accepted

#160 Transpose of a matrix
  Transpose2DArray.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#159 Added Selection sort program
  Java_DSA/Sorting/SelectionSort.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#129 Create Largest.java
  Largest.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#130 Create Reverse.java
  Reverse.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#158 tic-tac-toe game in java
  tic-tac-toe.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#149 Create a Maze.java file
  Java_DSA/Maze.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#131 FLOYD WARSHALL ALGORITHM
  FLOYD WARSHALL ALGORITHM.c
Labels: Hacktoberfest, Hacktoberfest-accepted

#144 Add files via upload
  MERGE SORT WITHOUT RECURSION.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#153 Create Generate a String With Characters That Have Odd Counts.java
  Generate a String With Characters That Have Odd Counts.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#166 Create binary search algorthim.java
  binary search algorthim.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#167 Array Rotation.cpp
  Array_Rotation.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#169 Added bubble sort algo in java
  .DS_Store
  buublesort.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#170 Strassen’sMatrixMultiplication
  Java_DSA/Strassen’sMatrixMultiplication.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#171 Create InsertingNode.java
  InsertingNode.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#175 Simple Calculator
  SimpleCalculator/CSS/style.css
  SimpleCalculator/HTML/index.html
  SimpleCalculator/IMG/calculatorTitle.png
  SimpleCalculator/JS/script.js
  SimpleCalculator/README.md
Labels: Hacktoberfest, Hacktoberfest-accepted

#173 missing number
  missingnumber
Labels: Hacktoberfest, Hacktoberfest-accepted

#182 Create FractionalKnapsack.java
  Java_DSA/FractionalKnapsack.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#181 Added LeetCode DSA problem
  Java_DSA/LeetCode_Same_Tree.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#191 Hacktoberfest2022
  kroneckerproduct.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#192 Create reverse_integer.cpp
  reverse_integer.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#190 HouseRobber Problem in Java
  Java_DSA/HouseRobber.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#183 added leetcode dsa questions
  C++_DSA/BinaryTreeInorderTraversal.cpp
  C++_DSA/BinaryTreeMinimumDepth.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#199 New files via upload
  Program15.cpp
  Program17.cpp
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted

#201 Adding few Basic dsa questions and concept for java
  Java_DSA/ShortestPathInAMaze.java
  Java_DSA/linkedLists/MainLinkedList.java
  Java_DSA/linkedLists/MyLinkedList.java
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted

#203 Create FibonacciNumberFunction.java
  FibonacciNumberFunction.java
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted
